site_name: BigFred
site_url: https://dcc-bigfred.github.io/docs/
repo_url: https://github.com/dcc-bigfred/docs
repo_name: dcc-bigfred/docs
edit_uri: edit/main/content/en/

docs_dir: content
exclude_docs: |
  LICENSE

theme:
  name: landing
  custom_dir: overrides

  favicon: assets/avatar.svg
  avatar: assets/avatar.svg
  tagline: |
    Modern, multi-user DCC driver supporting LocoNet and Z21
  footer: |
    Compiled from markdown using [MkDocs](https://www.mkdocs.org/). Theme is
    [Landing](https://teparsons.github.io/mkdocs-landing/) by
    [Todd Parsons](https://toddparsons.co.uk).
  page_source:
    link: https://github.com/dcc-bigfred/docs
    icon: [brands, github]
  socials:
    - label: GitHub
      link: https://github.com/dcc-bigfred
      icon: [brands, github]

  header_layout:
    - title
    - tagline
  share_btn: false
  content_box_opacity: 0
  avatar_size: 8rem
  round_avatar: true
  background_gradient_colors:
    - color-mix(in srgb, var(--crust) 100%, transparent)
    - color-mix(in srgb, var(--base) 80%, transparent)

  primary_color: "#dd7878"
  secondary_color: "#7287fd"
  tertiary_color: "#dd7878"
  base_color: "#24273a"
  mantle_color: "#1e2030"
  crust_color: "#181926"
  overlay_color: "#9B9B9E"
  text_color: "#c6d0f5"
  hltext_color: "#24273a"

  primary_color_dark: "#dd7878"
  secondary_color_dark: "#7287fd"
  tertiary_color_dark: "#dd7878"
  base_color_dark: "#24273a"
  mantle_color_dark: "#1e2030"
  crust_color_dark: "#181926"
  overlay_color_dark: "#9B9B9E"
  text_color_dark: "#c6d0f5"
  hltext_color_dark: "#24273a"

  body_font: Maven Pro
  heading_font: Oswald

extra:
  languages:
    en: English
    pl: Polski

extra_css:
  - assets/expanded-toc.css

plugins:
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: pl
          name: Polski
          build: true
          nav_translations:
            Home: Strona główna
            User guide: Przewodnik użytkownika
            Related: Powiązane
            Specifications: Specyfikacja
            Overview: Przegląd
            Locomotives and trains: Lokomotywy i składy
            Remotes: Piloty
  - search
  - awesome-pages
  - mermaid2

markdown_extensions:
  - tables
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - toc
